name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 93.189.90.34
          port: 2222
          username: rafa
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www/html/ProyectoFinalFront
            git pull origin master
            npm run build
